[verilog]
include_paths = ["./src","./test"]
defines = ["DEBUG", "VAR=1"]

[option]
linter = true
uppercamelcase_package = true
lowercamelcase_package = false
prefix_inout = "io_"
prefix_input = "i_"
prefix_output = "o_"
prefix_instance = "u_"
prefix_package = "pkg_"
